name: Deploy Node.js to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          npm run dev || echo "No build step found"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.0b14b0c2-80fe-42e8-9c62-c4ed8e568065}}
          tenant-id: ${{ secrets.9227cf50-83cd-43aa-9126-38802b38e5dc}}
          subscription-id: ${{ secrets.023c9b67-6531-46e0-be9b-b1cdbece5196}}
          client-secret: ${{ secrets.gIy8Q~d6b1UGC7ohFnX_EBvV.S1hTP~M_s213dfl}} # Ensure you have this set in GitHub Secrets

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Autobots'  # Your Azure Web App Name
          package: '.' # Deploy the root directory (must contain `server.js`)

      - name: Restart Azure Web App
        run: |
          az webapp restart --name Autobots --resource-group autobot
