name: Deploy PHP to Azure
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Autobots'
          package: './public'