name: Deploy Frontend & Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          npm run build || echo "No build script, skipping..."

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "autobots"
          package: "./backend"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-frontend:
    name: Deploy Frontend (React)
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "autobots-frontend"
          package: "./frontend/build"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS}}