name: Deploy Frontend & Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy-backend:
    name: Deploy Backend (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: backend  # 🔥 Fix: Now runs inside "backend"

      - name: Build Backend
        run: npm run build || echo "No build script, skipping..."
        working-directory: backend  # 🔥 Fix: Now runs inside "backend"

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "autobots"
          package: "./backend"
          
  deploy-frontend:
     name: Deploy Frontend (React + Vite)
     runs-on: ubuntu-latest
     needs: deploy-backend
     steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Frontend Dependencies
        run: |
            cd frontend
            npm ci || npm install
        
      - name: Build Frontend
        run: |
            cd frontend
            npm run build  # ✅ This will now output to `build/` instead of `dist/`
        
      - name: Verify Frontend Build
        run: |
            ls -la frontend/build  # ✅ Ensure `build/` exists before deployment
        
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "autobots-frontend"
          package: "./frontend/dist"
        
