name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend  # Added working directory
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI tests (optional)
        run: pytest backend/tests || echo "Tests failed, continuing deployment"

      - name: Deploy FastAPI to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: autobots
          package: ./backend
          slot-name: production

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend  # Separate cd command
          npm install
          npm run build

      - name: Deploy React frontend to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.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 }} # Double-check this token
          action: "upload"
          app_location: "/frontend/build"  # Corrected path
          output_location: "" # Empty for Azure Static Web Apps
