name: Deploy Full Stack to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME_BACKEND: tradesmen-backend
  AZURE_WEBAPP_NAME_FRONTEND: tradesmen-frontend
  AZURE_RESOURCE_GROUP: tradesmen-app-rg
  AZURE_LOCATION: australiaeast
  AZURE_WEBAPP_PACKAGE_PATH_BACKEND: ./tradesman-backend
  AZURE_WEBAPP_PACKAGE_PATH_FRONTEND: ./tradesman-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        path: ./

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Azure Web Apps Exist
      run: |
        az group create --name $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION
        az webapp create --resource-group $AZURE_RESOURCE_GROUP --plan ASP-TradesmenApp-be2a --name $AZURE_WEBAPP_NAME_BACKEND --runtime "NODE|18-lts" --output none || echo "Backend Web App already exists."
        az webapp create --resource-group $AZURE_RESOURCE_GROUP --plan B1 --name $AZURE_WEBAPP_NAME_FRONTEND --runtime "NODE|18-lts" --output none || echo "Frontend Web App already exists."

    - name: Verify Directory Structure
      run: |
        echo "Checking available directories:"
        ls -al
        echo "Checking project structure recursively:"
        find . -maxdepth 2

    - name: Install Dependencies (Backend)
      run: |
        if [ -d "$AZURE_WEBAPP_PACKAGE_PATH_BACKEND" ]; then
          cd $AZURE_WEBAPP_PACKAGE_PATH_BACKEND
          npm install
        else
          echo "Backend directory not found!" && exit 1
        fi

    - name: Deploy Backend to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_BACKEND }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}

    - name: Install Dependencies (Frontend)
      run: |
        if [ -d "$AZURE_WEBAPP_PACKAGE_PATH_FRONTEND" ]; then
          cd $AZURE_WEBAPP_PACKAGE_PATH_FRONTEND
          npm install
          npm run build
        else
          echo "Frontend directory not found!" && exit 1
        fi

    - name: Deploy Frontend to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_FRONTEND }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}/build
